---
General:
  amp: true
  device: cuda:0
  task: gan-ves-seg
  inference: G
  model:
    name: GanSegModel
    model_g:
      name: resnetGenerator9
    model_d: 
      name: patchGAN70x70
    model_s:
      name: DynUNet
      spatial_dims: 2
      in_channels: 1
      out_channels: 1
      kernel_size: [3,3,3,3,3]
      strides: [1,2,2,2,1]
      upsample_kernel_size: [1,2,2,2,1]
    compute_identity: false
    compute_identity_seg: true
Train:
  data:
    real_B:
      # files: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images
      files: /home/shared/Data/Munich_macular_holes
      suffix: .png
      # split: /home/lkreitner/OCTA-seg/datasets/OCTA-500_healthy/train_
    real_A:
      files: /home/lkreitner/OCTA-seg/datasets/synth_0008/synth_0008_304x304_full/**/*.png
    real_A_seg:
      files: /home/lkreitner/OCTA-seg/datasets/synth_0008/synth_0008_1216x1216_full/**/*.png
    files:
      files: /home/linus/repos/OCTA-seg/datasets/background_images/**/*.png
  epochs: 100
  epochs_decay: 0
  save_interval: 25
  batch_size: 4
  lr: 0.0002
  loss_dg: LSGANLoss
  loss_s: DiceBCELoss
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      image_only: true
    - name: ToGrayScaled
      keys:
        - real_B
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      strict_check: false
    # - name: Resized
    #   keys:
    #   - real_B
    #   spatial_size:
    #   - 304
    #   - 304
    #   mode: bilinear
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      minv: 0
      maxv: 1
    - name: RandFlipd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - real_A
      # - real_B
      - real_A_seg
      - files
      prob: 0.75
    - name: CenterSpatialCropd
      keys:
        - real_A
        - files
      roi_size: [256,128]
    - name: CenterSpatialCropd
      keys:
        - real_A_seg
      roi_size: [1024,512]
    - name: Rotate90d
      keys:
        - real_B
    - name: RandRotated
      keys:
        - real_B
      prob: 0.5
      range_x: [3.141592653589793,3.141592653589793]
    - name: RandRotated
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      minv: 0
      maxv: 1
    - name: AsDiscreted
      keys:
      - real_A_seg
      threshold: 0.1
    - name: AddRandomGaussianNoiseChanneld
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_A_seg
      - real_B
      dtype: dtype
  post_processing:
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 160
    label: null
Validation:
  batch_size: 4
Test:
  batch_size: 1
  data:
    real_B:
      files: /home/shared/Data/Munich_macular_holes/**/*.png
    real_A:
      files: /home/lkreitner/OCTA-seg/datasets/synth_0025/synth_0025_304x304_full/**/*.png
    files:
      files: /home/lkreitner/OCTA-seg/datasets/files_11_11_22/**/*.png
  save_comparisons: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      allow_missing_keys: true
      image_only: true
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      allow_missing_keys: true
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      allow_missing_keys: true
      strict_check: false
    - name: Rotate90d
      allow_missing_keys: true
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      k: 1
    - name: Flipd
      allow_missing_keys: true
      keys:
      - real_A
      - real_B
      - real_A_seg
      - files
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - real_A_seg
      allow_missing_keys: true
      threshold: 0.1
    - name: AddRandomGaussianNoiseChanneld
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_A_seg
      - real_B
      allow_missing_keys: true
      dtype: dtype
  post_processing:
    # Only if inference=S, else:
    # prediction: null
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 160
    label: null
Output:
  save_dir: /home/lkreitner/OCTA-seg/results/gan-ves-seg
  save_to_disk: true
  save_to_tensorboard: true
