---
General:
  amp: true
  device: cuda:0
  task: gan-ves-seg
  inference: netG_A
  model:
    name: NiceGAN
    gen2B_config:
      name: NiceResnetGenerator
      input_nc: 1
      output_nc: 1
      ngf: 64
      n_blocks: 6
      img_size: 304
      # img_size: 256
      light: True
    gen2A_config:
      name: NiceResnetGenerator
      input_nc: 1
      output_nc: 1
      ngf: 64
      n_blocks: 6
      img_size: 304
      # img_size: 256
      light: True
    disA_config: 
      name: NiceDiscriminator
      input_nc: 1
      ndf: 64
      n_layers: 7
    disB_config: 
      name: NiceDiscriminator
      input_nc: 1
      ndf: 64
      n_layers: 7
    adv_weight: 1
    cycle_weight: 10
    recon_weight: 1
Train:
  data:
    real_B:
      # files: /home/linus/Datasets/OCTA/processed/OCTA_TUMNeuro_initial_3_qc_combined/*.png
      files: /home/linus/Datasets/OCTA/OCTA-500/processed/images/*.png
      split: /home/linus/Datasets/OCTA/OCTA-500/processed/train_
      # files: /home/linus/repos/OCTA-seg/datasets/OCTA_TUMNeuro_prototyping/*.png
      # files: /home/shared/Data/Munich_macular_holes/*.png
      # files: /home/shared/Data/WEH_OCTA/*.png
    real_A:
      files: /home/linus/repos/OCTA-seg/datasets/vessel_graphs/*.csv
    background:
      files: /home/linus/repos/OCTA-seg/datasets/background_images/*.png
  epochs: 100
  epochs_decay: 0
  save_interval: 25
  val_interval: 200
  batch_size: 4
  lr: 0.0001
  loss_ad: MSELoss
  loss_cycle: L1Loss
  weight_decay: 0.0001
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_B
      - background
      image_only: true
    - name: ToGrayScaled
      keys:
        - real_B
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - real_A
      image_resolutions: 
        - [304,304] # for 304x304 images
        # - [256,256]
      min_radius: [0,0]
      max_dropout_prob: 0.02
      # radius_range: [0.0001, 0.0015]
      # p_exp: 2
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - background
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - real_B
      - background
      spatial_size:
      - 304
      - 304
      # - 256
      # - 256
      mode: bilinear
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - background
      minv: 0
      maxv: 1
    - name: RandFlipd
      keys:
      - real_A
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - real_A
      prob: 0.75
    - name: RandFlipd
      keys:
      - real_B
      - background
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - real_B
      - background
      prob: 0.75
    - name: RandRotated
      keys:
      - real_A
      - real_B
      - background
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: CastToTyped
      keys:
      - real_A
      - real_B
      - background
      dtype: dtype
  post_processing:
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 40
    label:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 40
Test:
  batch_size: 1
  data:
    real_B:
      files: /home/linus/Datasets/OCTA/OCTA-500/processed/images/*.png
      split: /home/linus/Datasets/OCTA/OCTA-500/processed/val_
    real_A:
      files: /home/linus/Datasets/OCTA/OCTA_synth/dataset_16_02_23/*.csv
    background:
      files: /home/linus/repos/OCTA-seg/datasets/background_images/*.png
  save_comparisons: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_B
      - background
      allow_missing_keys: true
      image_only: true
    - allow_missing_keys: true
      name: ToGrayScaled
      keys:
        - real_B
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - real_A
      image_resolutions: 
        - [304,304]
      allow_missing_keys: true
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - background
      allow_missing_keys: true
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - background
      allow_missing_keys: true
      channel_dim: no_channel
      strict_check: false
    - name: Rotate90d
      allow_missing_keys: true
      keys:
      # - real_A
      - real_B
      - background
      k: 1
    - name: Flipd
      allow_missing_keys: true
      keys:
      # - real_A
      - real_B
      - background
      spatial_axis: 0
    - name: AddRandomBackgroundNoised
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_B
      allow_missing_keys: true
      dtype: dtype
  post_processing:
    prediction: null
    label: null
Output:
  save_dir: /home/linus/repos/OCTA-seg/results/niceGAN
  save_to_disk: true
  save_to_tensorboard: false
