---
General:
  amp: true
  device: cuda:0
  task: ves-seg
  model:
    name: DynUNet
    spatial_dims: 2
    in_channels: 1
    out_channels: 44
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
Train:
  data:
    image:
      files: /home/linus/repos/OCTA-seg/datasets/vessel_graphs/*.csv
    label:
      files: /home/linus/Datasets/OCTA/OCTA_synth/dataset_3d_diverse/*.nii.gz
    blackdict:
      files: /home/linus/Datasets/OCTA/OCTA_synth/dataset_3d_diverse/*_blackdict.pkl
  epochs: 60
  epochs_decay: 10
  val_interval: 100
  save_interval: 5
  batch_size: 4
  lr: 0.0001
  loss: DiceBCELoss
  AT: false
  data_augmentation:
    - name: LoadImaged
      keys:
        - label
      image_only: true
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - image
      image_resolutions: 
        - [1216,1216]
      max_dropout_prob: 0
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
      channel_dim: no_channel
    - name: EnsureChannelFirstd
      keys:
      - label
      strict_check: false
      channel_dim: 2
    - name: SelectSlice
      keys:
      - label
      slice_selection: [[5,-4]]
    - name: RandFlipd
      keys:
      - image
      - label
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - image
      - label
      prob: 0.75
    - name: RandRotated
      keys:
      - image
      - label
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: AsDiscreted
      keys:
      - image
      - label
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      # min_size: 128
      min_size: 16
    - name: AsChannelLast
      channel_dim: 0
    label:
    - name: CastToType
      dtype: uint8
    - name: AsChannelLast
      channel_dim: 0
Test:
  batch_size: 1
  data:
    image:
      files: /home/linus/repos/OCTA-seg/datasets/vessel_graphs/*.csv
  data_augmentation:
    - name: LoadImaged
      keys:
        - image
      image_only: true
    - name: ScaleIntensityd
      keys:
      - image
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
      channel_dim: no_channel
    - name: Rotate90d
      keys:
      - image
      k: 1
    - name: Flipd
      keys:
      - image
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - image
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      # min_size: 128
      min_size: 16
    - name: AsChannelLast
      channel_dim: 0
Output:
  save_dir: ./results/recon-supervised
  save_to_disk: true
  save_to_tensorboard: false
  save_interval: 1