---
General:
  amp: true
  device: cuda:0
  task: ves-seg
  model:
    name: DynUNet
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
Train:
  data:
    image:
      files: /home/linus/repos/OCTA-seg/datasets/vessel_graphs/**/*.csv
    label:
      files: /home/linus/repos/OCTA-seg/datasets/vessel_graphs/**/*.csv
    background:
      files: /home/linus/repos/OCTA-seg/datasets/background_images/**/*.png
  epochs: 20
  epochs_decay: 10
  val_interval: 1
  save_interval: 2
  batch_size: 4
  lr: 0.0001
  loss: DiceBCELoss
  AT: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - background
      image_only: true
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - image
        - label
      image_scales: [6.73,16]
      # min_radius: [0,0.0033]
      # min_radius: [0,0.0015]
      min_radius: [0,0]
      max_dropout_prob: 0.02
    - name: ScaleIntensityd
      keys:
      - image
      - label
      - background
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      - background
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - background
      spatial_size:
      - 512
      - 512
      mode: bilinear
    - name: AddRandomBackgroundNoised
      keys:
        - image
      delete_background: False
    - name: ImageToImageTranslationd
      model_path: /home/linus/repos/OCTA-seg/results/gan-ves-seg/20230529_230017/checkpoints/125_G_model.pth
      # model_path: /home/lkreitner/OCTA-seg/results/gan-ves-seg/20230206_145635/checkpoints/150_G_model.pth 
      keys:
        - image
    - name: NoiseModeld
      keys:
        - image
      prob: 0.5
      lambda_delta: 0.4
      lambda_speckle: 0.4
      lambda_gamma: 0.1
      downsample_factor: 1
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    # - name: SpeckleBrightnesd
    #   keys:
    #     - image
    - name: RandFlipd
      keys:
      - image
      - label
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - image
      - label
      prob: 0.75
    - name: RandRotated
      keys:
      - image
      - label
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
Validation:
  batch_size: 4
  data:
    image:
      files: /home/linus/Datasets/OCTA/processed/OCTA_TUMNeuro_initial_3/**/*.png
      split: /home/linus/Datasets/OCTA/processed/OCTA-500/val_0.txt
    label:
      files: /home/linus/Datasets/OCTA/processed/OCTA_TUMNeuro_initial_3/**/*.png
      split: /home/linus/Datasets/OCTA/processed/OCTA-500/val_0.txt
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ToGrayScaled
      keys:
        - image
        - label
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      - label
      k: 1
    - name: Flipd
      keys:
      - image
      - label
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.5
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 128
    label:
    - name: CastToType
      dtype: uint8
Test:
  batch_size: 1
  data:
    image:
      files: /home/linus/Datasets/OCTA/processed/OCTA_TUMNeuro_initial_3/**/*.png
  save_comparisons: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      image_only: true
    - name: ToGrayScaled
      keys:
      - image
    - name: ScaleIntensityd
      keys:
      - image
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      k: 1
    - name: Flipd
      keys:
      - image
      spatial_axis: 0
    - name: CastToTyped
      keys:
      - image
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 128
    label:
    - name: CastToType
      dtype: uint8
Output:
  save_dir: /home/linus/repos/OCTA-seg/results/ves-seg-S_GAN
  save_to_disk: true
  save_to_tensorboard: true