---
Greenhouse:
  SimulationSpace:
    no_voxel_x: 1 
    no_voxel_y: 1
    no_voxel_z: 0.0131
  d: 0.1
  r: 0.0025
  FAZ_radius_bound:
    - 0.44
    - 0.04
  rotation_radius: 1.05
  FAZ_center:
    - 0.5
    - 0.5
  nerve_center: [10.56,5.16]
  nerve_radius: 0.3
  param_scale: 3
  modes:
    - name: SVC
      I: 100
      N: 2000
      eps_n: 0.18
      eps_s: 0.135
      eps_k: 0.135
      delta_art: 0.2925
      delta_ven: 0.2925
      gamma_art: 50
      gamma_ven: 50
      phi: 15
      omega: 0.3
      kappa: 2.55
      delta_sigma: 0.02
    - name: DVC
      I: 150
      N: 2000
      eps_n: 0.09
      eps_s: 0.0675
      eps_k: 0.0675
      delta_art: 0.14625
      delta_ven: 0.14625
      gamma_art: 90
      gamma_ven: 90
      phi: 15
      omega: 0
      kappa: 2.9
      delta_sigma: 0.02
output:
  directory: /var/generation/vessel_graphs
  # image_scale_factor: 304
  #for 640x640 images
  image_scale_factor: 640
  save_trees: true
  save_3D_volumes: null
  save_2D_image: true
  proj_axis: 2
  save_stats: false
Forest:
  type: stumps
  N_trees: 8
  source_walls:
    x0: true
    x1: true
    y0: true
    y1: true
    z0: false
    z1: false
