---
Greenhouse:
  modes:
    - SVC
    - DVC
  d: 0.1
  r: 0.0025
  FAZ_radius_bound:
    - 0.44
    - 0.04
  rotation_radius: 1.05
  FAZ_center:
    - 0.5
    - 0.5
  param_scale: 3
  SVC:
    I: 100
    N: 2000
    eps_n: 0.18
    eps_s: 0.135
    eps_k: 0.135
    delta_art: 0.2925
    delta_ven: 0.2925
    gamma_art: 50
    gamma_ven: 50
    phi: 15
    omega: 0.3
    kappa: 2.55
    delta_sigma: 0.02
    SimulationSpace:
      no_voxel_x: 76
      no_voxel_y: 76
      no_voxel_z: 1
      oxygen_sample_geometry_path: /home/OCTA-seg/vessel_graph_generation/geometries/slab_oxy_sample_3mm.npy
      tree_root_indices_path: ''
  DVC:
    I: 150
    N: 2000
    eps_n: 0.09
    eps_s: 0.0675
    eps_k: 0.0675
    delta_art: 0.14625
    delta_ven: 0.14625
    gamma_art: 90
    gamma_ven: 90
    phi: 15
    omega: 0
    kappa: 2.9
    delta_sigma: 0.02
output:
  directory: /var/generation/synth_csv
  subdir_with_timestamp: true
  image_scale_factor: 4
  save_trees: true
  save_3D_volumes: false
  save_art: false
  save_ven: false
  save_art_ven_gray: true
  save_art_ven_rgb: false
  save_art_ven_gray_noise: false
  save_proj:
    - 2
  save_stats: false
  save_nii: false
Forest:
  type: stumps
  N_trees: 8
  d_0: 0.045
  r_0: 0.001
  source_walls:
    x0: true
    x1: true
    y0: true
    y1: true
    z0: false
    z1: false
