---
#############################################################################################
# This is a template for new configuration files.
# It contains sample values and explainations for every variable.
# 
# "Mandatory" denotes that the key must exist.
# "Default: XY" denotes that if no key-value pair is provided, the default value will be used
#############################################################################################

# Mandatory - General settings needed in multiple settings
General:
  # Default: False - Whether to train with automated mixed precision https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html
  amp: true
  # Default: 'cpu' - Device to use. Either "cpu", "cuda", or "cuda:X", where X is the index of the gpu
  device: cuda:0
  # Mandatory - Task to perform. See class Task in './utils/metrics.py'
  task: ves-seg
  # Mandatory - Model / Network to use.
  model:
    # Name of the model. See MODEL_DICT in ./models/networks.py
    name: DynUNet
    # List all parameters for the model...
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
# Mandatory for Training - Training settings
Train:
  # Mandatory - Dataset settings
  data:
    # List the keys that are required by the model...

    # Image files
    image:
      # Mandatory - Dataset folder. Use absolute paths
      folder: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER
      # Mandatory - Suffix of the files to load. Will load all files *.csv from the folder
      suffix: .csv
      # Default: Use all files - Path of a file listing all indices of the files that should be loaded
      split: null
    # Label files
    label:
      folder: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER
      suffix: .csv
      split: null
    deep:
      folder: /ABSOLUTE/PATH/TO/SYNTHETIC/DEEP/CSV/FOLDER
      suffix: .png
  # Mandatory - Number of epochs to train
  epochs: 30
  # Default: 0 - Number of epochs to linearly decay learning rate
  epochs_decay: 10
  # Default: 1 - Epoch interval to perform valdiation
  val_interval: 1
  # Default: 1 - Epoch interval to store checkpoints
  save_interval: 5
  # Default: 1 - Batch size
  batch_size: 4
  # Mandatory - (Start) learning rate
  lr: 0.0001
  # Mandatory - Loss function. See get_loss_function_by_name() in ./utils/losses.py
  loss: DiceBCELoss
  # Default: false - Adversarial training. Only effective when NoiseModeld data transformation is used
  AT: false
  # Mandatory - Data augmentation. We use custom data transforms from ./data/data_transfroms.py and from https://docs.monai.io/en/stable/transforms.html
  data_augmentation:
    # List all data transforms in the order they should be run.
    # Make sure to use the same key names as used in the data block.

    # Mandatory - Name of the data transform.
    - name: LoadImaged
      # Mandatory - List of all items the transform should be applied to.
      keys:
      - deep
      # Other parameters...
      image_only: true
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - image
        - label
      image_scales: [4,16]
      min_radius: [0,0]
      max_dropout_prob: 0.02
    - name: ScaleIntensityd
      keys:
      - image
      - label
      - deep
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      - deep
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Resized
      keys:
      - deep
      spatial_size:
      - 304
      - 304
      mode: bilinear
    - name: NoiseModeld
      keys:
        - image
      prob: 0.5
      lambda_delta: 0.7
      lambda_speckle: 0.5
      lambda_gamma: 0.1
      downsample_factor: 1
    - name: RandomDecreaseResolutiond
      keys:
        - image
    - name: RandFlipd
      keys:
      - image
      - label
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - image
      - label
      prob: 0.75
    - name: RandRotated
      keys:
      - image
      - label
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.5
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  # Mandatory - Post processing transforms that should be applied before computing the metric / the final output.
  # We use custom data transforms from ./data/data_transfroms.py and from https://docs.monai.io/en/stable/transforms.html
  post_processing:
    # Default: None - Post processing for the models prediction.
    prediction:
    # Mandatory - Name of the transform
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    # Default: None - Post processing for the label.
    label:
    - name: CastToType
      dtype: uint8
# Mandatory for Validation - Validation settings
Validation:
  batch_size: 4
  data:
    image:
      suffix: .png
      folder: /ABSOLUTE/PATH/TO/OCTA-500/images
      split: /ABSOLUTE/PATH/TO/OCTA-500/val_0.txt
    label:
      suffix: .png
      folder: /ABSOLUTE/PATH/TO/OCTA-500/segmentations
      split: /ABSOLUTE/PATH/TO/OCTA-500/val_0.txt
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      - label
      k: 1
    - name: Flipd
      keys:
      - image
      - label
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.5
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
# Mandatory for Testing - Test settings
Test:
  batch_size: 1
  data:
    image:
      suffix: .png
      folder: /ABSOLUTE/PATH/TO/OCTA-500/images
      split: /ABSOLUTE/PATH/TO/OCTA-500/val_0.txt
  # Default: Infinity - Maximum number of samples used for inference
  num_samples: 10
  # Default: false - Create a side by side comparison of the source and prediction
  save_comparisons: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      image_only: true
    - name: ToGrayScaled
      keys:
      - image
    - name: ScaleIntensityd
      keys:
      - image
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      k: 1
    - name: Flipd
      keys:
      - image
      spatial_axis: 0
    - name: CastToTyped
      keys:
      - image
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
  # Default: Output.save_dir + /test - Save directory to store test results
  save_dir: /ABSOLUTE/PATH/TO/results/template/
# Mandatory - Output settings
Output:
  # Mandatory - Save directory to store checkpoints, training details, etc.
  save_dir: /ABSOLUTE/PATH/TO/results/template/
  # Mandatory - If true, store example images during training as images in the save folder.
  save_to_disk: true
  # Mandatory - If true, store example images during training in tensorboard
  save_to_tensorboard: true