---
General:
  amp: true
  device: cuda:0
  task: gan-ves-seg
  inference: G
  model:
    name: GanSegModel # Model name
    model_g:
      name: resnetGenerator9
    model_d: 
      name: patchGAN70x70
    model_s:
      name: DynUNet
      spatial_dims: 2
      in_channels: 1
      out_channels: 1
      kernel_size: [3,3,3,3,3]
      strides: [1,2,2,2,1]
      upsample_kernel_size: [1,2,2,2,1]
    compute_identity: false
    compute_identity_seg: true
Train:
  data:
    real_B:
      files: /home/OCTA-seg/OCTA500/images/**/*.png
      # split: Optional: /PATH/TO/YOUR/INDEX/FILE
    real_A:
      files: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER/**/*.csv 
    real_A_seg:
      files: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER/**/*.csv  
    background:
      files: /home/OCTA-seg/datasets/background_images/**/*.png
  epochs: 100
  epochs_decay: 0
  save_interval: 25
  batch_size: 4
  lr: 0.0002
  loss_dg: LSGANLoss
  loss_s: DiceBCELoss
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_B
      - background
      image_only: true
    - name: ToGrayScaled
      keys:
        - real_B
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - real_A
        - real_A_seg
      image_resolutions: 
        # - [304,304] # for 304x304 images3
        # - [1216,1216]
        - [640,640] # for 640x640 images3
        - [1216,1216]
        # - [512,512] # for 512x512 images3
        # - [1216,1216]
      min_radius: [0,0]
      max_dropout_prob: 0.02
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - background
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - background
      - real_B
      spatial_size:
      # - 304
      # - 304
      - 640
      - 640
      # - 512
      # - 512
      mode: bilinear
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - background
      minv: 0
      maxv: 1
    - name: RandFlipd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - background
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - real_A
      - real_B
      - real_A_seg
      - background
      prob: 0.75
    - name: RandRotated
      keys:
      - real_A
      - real_B
      - real_A_seg
      - background
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      minv: 0
      maxv: 1
    - name: AsDiscreted
      keys:
      - real_A_seg
      threshold: 0.1
    - name: AddRandomBackgroundNoised
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_A_seg
      - real_B
      dtype: dtype
  post_processing:
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 160
    label: null
Test:
  batch_size: 1
  data:
    real_B:
      files: datasets/images3/*.png
      # split: Optional: /PATH/TO/YOUR/INDEX/FILE
    real_A:
      files: datasets/vessel_graphs/*.csv
    # /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER/**/*.csv
    real_A_seg:
      files: datasets/vessel_graphs/*.csv 
      # datasets/labels/GT_Artery/*.bmp
    background:
      files: datasets/background_images/*.png
  save_comparisons: false
  data_augmentation:
  
    - name: LoadImaged
      keys:
      - real_B
      - background
      allow_missing_keys: true
      image_only: true
    - allow_missing_keys: true
      name: ToGrayScaled
      keys:
        - real_B
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - real_A
      
      image_resolutions: 
        # - [304,304]
        - [640,640]
      allow_missing_keys: true
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - background
      allow_missing_keys: true
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - background
      allow_missing_keys: true
      channel_dim: no_channel
      strict_check: false
    - name: Rotate90d
      allow_missing_keys: true
      keys:
      - real_B
      - background
      k: 1
    - name: Flipd
      allow_missing_keys: true
      keys:
      - real_B
      - background
      spatial_axis: 0
    - name: AddRandomBackgroundNoised
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_B
      allow_missing_keys: true
      dtype: dtype
  post_processing:
    # Only if inference=S, else:
    # prediction: null
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 160
    label: null 

Validation:
  batch_size: 4
  data:
    real_B:
      files: datasets/images3/*.png
    real_A:
      files: datasets/vessel_graphs/*.csv
    real_A_seg:
      files: datasets/vessel_graphs/*.csv
    background:
      files: datasets/background_images/*.png
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_B
      - background
      image_only: true
    - name: ToGrayScaled
      keys:
        - real_B
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - real_A
      image_resolutions:
        - [640,640]
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - background
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - background
      channel_dim: no_channel
      strict_check: false
    - name: CastToTyped
      keys:
      - real_A
      - real_B
      dtype: dtype
  post_processing:
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 160
    label: null

Output:
  save_dir: ./results/gan-ves-seg # /PATH/TO/YOUR/RESULTS/FOLDER
  save_to_disk: true
  save_to_tensorboard: false
