---
General:
  amp: true
  device: cuda:0
  task: ves-seg
  model:
    name: DynUNet
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
Train:
  data:
    image:
      folder: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER
      suffix: .csv
    label:
      folder: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER
      suffix: .csv
    deep:
      folder: /ABSOLUTE/PATH/TO/SYNTHETIC/DEEP/CSV/FOLDER
      suffix: .png
  epochs: 30
  epochs_decay: 10
  val_interval: 1
  save_interval: 2
  batch_size: 4
  lr: 0.0001
  loss: DiceBCELoss
  AT: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - deep
      image_only: true
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - image
        - label
      image_scales: [4,16]
      min_radius: [0,0.0033] # OCTA-500
      # min_radius: [0,0.0015] # ROSE-1
      # min_radius: [0,0] # Giarratano (detailed)
      max_dropout_prob: 0.02
    - name: ScaleIntensityd
      keys:
      - image
      - label
      - deep
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      - deep
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - deep
      spatial_size:
      - 304
      - 304
      mode: bilinear
    - name: NoiseModeld
      keys:
        - image
      prob: 0.5
      lambda_delta: 0.7
      lambda_speckle: 0.5
      lambda_gamma: 0.1
      downsample_factor: 1
    - name: RandomDecreaseResolutiond
      keys:
        - image
    - name: RandFlipd
      keys:
      - image
      - label
      prob: 1
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - image
      - label
      prob: 0.75
    - name: RandRotated
      keys:
      - image
      - label
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
Validation:
  batch_size: 4
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images
      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/images
      # folder: /home/lkreitner/OCTA-seg/datasets/Giarratano/original_images
      suffix: .png
      split: /home/lkreitner/OCTA-seg/datasets/OCTA-500/val_4.txt
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_4.txt
      # split: /home/lkreitner/OCTA-seg/datasets/Giarratano/val_4.txt
    label:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/segmentations
      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/segmentations
      # folder: /home/lkreitner/OCTA-seg/datasets/Giarratano/segmented_images
      suffix: .png
      split: /home/lkreitner/OCTA-seg/datasets/OCTA-500/val_4.txt
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_4.txt
      # split: /home/lkreitner/OCTA-seg/datasets/Giarratano/val_4.txt
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ToGrayScaled
      keys:
        - image
        - label
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      - label
      k: 1
    - name: Flipd
      keys:
      - image
      - label
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.5
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 128
    label:
    - name: CastToType
      dtype: uint8
Test:
  batch_size: 1
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images
      spilt: /home/lkreitner/OCTA-seg/datasets/OCTA-500/test_0.txt
      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/images
      # spilt: /home/lkreitner/OCTA-seg/datasets/ROSE-1/test_0.txt
      suffix: .png
  num_samples: 10
  save_comparisons: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      image_only: true
    - name: ToGrayScaled
      keys:
      - image
    - name: ScaleIntensityd
      keys:
      - image
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      spatial_size:
      - 1216
      - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      k: 1
    - name: Flipd
      keys:
      - image
      spatial_axis: 0
    - name: CastToTyped
      keys:
      - image
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 128
    label:
    - name: CastToType
      dtype: uint8
Output:
  save_dir: ./results/ves-seg-S_RA
  save_to_disk: true
  save_to_tensorboard: true