---
General:
  amp: true
  device: cuda:0
  task: ves-seg
  model:
    name: DynUNet
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
Train:
  data:
    image:
      files: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER/**/*.csv
    label:
      files: /ABSOLUTE/PATH/TO/SYNTHETIC/CSV/FOLDER/**/*.csv
    background:
      files: /ABSOLUTE/PATH/TO/SYNTHETIC/BACKGROUND/FOLDER/**/*.png
  epochs: 30
  epochs_decay: 10
  val_interval: 1
  save_interval: 5
  batch_size: 4
  lr: 0.0001
  loss: DiceBCELoss
  AT: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - background
      image_only: true
    - name: LoadGraphAndFilterByRandomRadiusd
      keys:
        - image
        - label
      image_resolutions: 
        - [304,304] # for 304x304 images
        - [1216,1216]
        # - [512,512] # for 512x512 images
        # - [1216,1216]
      # min_radius: [0,0.0033] # OCTA-500
      # min_radius: [0,0.0015] # ROSE-1
      min_radius: [0,0] # Giarratano (detailed)
      max_dropout_prob: 0.02
    - name: ScaleIntensityd
      keys:
      - image
      - label
      - background
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      - background
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - background
      spatial_size:
      - 304
      - 304
      # - 512
      # - 512
      mode: bilinear
    - name: AddRandomBackgroundNoised
      keys:
        - image
      delete_background False
    - name: ImageToImageTranslationd
      model_path: /ABSOLUTE/PATH/TO/checkpoints/125_G_model.pth
      keys:
        - image
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
        # Giarratano
        # - 360
        # - 360
        # OCTA-500 and ROSE-1
        - 1216
        - 1216
      mode: bilinear
    - name: SpeckleBrightnesd
      keys:
        - image
    - name: RandFlipd
      keys:
      - image
      - label
      prob: 1
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - image
      - label
      prob: 0.75
    - name: RandRotated
      keys:
      - image
      - label
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    # For Giarratano
    # - name: RandCropOrPadd
    #   keys:
    #     - image
    #     - label
    #   prob: 1
    #   min_factor: 0.2965
    #   max_factor: 0.2965
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
Validation:
  batch_size: 4
  data:
    image:
      files: /ABSOLUTE/PATH/TO/OCTA-500/images/**/*.png
      # files: /ABSOLUTE/PATH/TO/ROSE-1/images/**/*.png
      # files: /ABSOLUTE/PATH/TO/Giarratano/original_images/**/*.png
      split: /ABSOLUTE/PATH/TO/OCTA-500/val_0.txt
      # split: /ABSOLUTE/PATH/TO/ROSE-1/val_0.txt
      # split: /ABSOLUTE/PATH/TO/Giarratano/val_0.txt
    label:
      files: /ABSOLUTE/PATH/TO/OCTA-500/segmentations/**/*.png
      # files: /ABSOLUTE/PATH/TO/ROSE-1/segmentations/**/*.png
      # files: /ABSOLUTE/PATH/TO/Giarratano/segmented_images/**/*.png
      split: /ABSOLUTE/PATH/TO/OCTA-500/val_0.txt
      # split: /ABSOLUTE/PATH/TO/ROSE-1/val_0.txt
      # split: /ABSOLUTE/PATH/TO/Giarratano/val_0.txt
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ToGrayScaled
      keys:
        - image
        - label
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
        # Giarratano
        # - 360
        # - 360
        # OCTA-500 and ROSE-1
        - 1216
        - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      - label
      k: 1
    - name: Flipd
      keys:
      - image
      - label
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.5
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 128
    label:
    - name: CastToType
      dtype: uint8
Test:
  batch_size: 1
  data:
    image:
      files: /ABSOLUTE/PATH/TO/OCTA-500/images/**/*.png
      # files: /ABSOLUTE/PATH/TO/ROSE-1/images/**/*.png
      # files: /ABSOLUTE/PATH/TO/Giarratano/original_images/**/*.png
      split: /ABSOLUTE/PATH/TO/OCTA-500/test_0.txt
      # split: /ABSOLUTE/PATH/TO/ROSE-1/test_0.txt
      # split: /ABSOLUTE/PATH/TO/Giarratano/test_0.txt
  save_comparisons: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      image_only: true
    - name: ToGrayScaled
      keys:
      - image
    - name: ScaleIntensityd
      keys:
      - image
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
      channel_dim: no_channel
    - name: Resized
      keys:
      - image
      spatial_size:
        # Giarratano
        # - 360
        # - 360
        # OCTA-500 and ROSE-1
        - 1216
        - 1216
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      k: 1
    - name: Flipd
      keys:
      - image
      spatial_axis: 0
    - name: CastToTyped
      keys:
      - image
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 128
    label:
    - name: CastToType
      dtype: uint8
Output:
  save_dir: ./ves-seg-S_GAN
  save_to_disk: true
  save_to_tensorboard: true